// AUTO-GENERATED by scripts/generate-leg-maps.mjs — do not edit by hand.
// Map tiles © OpenStreetMap contributors (openstreetmap.org/copyright).
window.legMaps = {
  "swim": {
    "zoom": 15,
    "pxX0": 4359943,
    "pxY0": 2983160,
    "width": 413,
    "height": 473,
    "src": "assets/maps/swim.png"
  },
  "bike": {
    "zoom": 11,
    "pxX0": 272292,
    "pxY0": 186239,
    "width": 425,
    "height": 531,
    "src": "assets/maps/bike.png"
  },
  "run": {
    "zoom": 14,
    "pxX0": 2179675,
    "pxY0": 1493185,
    "width": 409,
    "height": 511,
    "src": "assets/maps/run.png"
  }
};
